"""Embeds web/mindmodel.js and mindcore/model/*.mind into mind_sandbox.html (between //MINDMODEL_START and //MINDMODEL_END).
Usage: python tools/build_html.py [--check]"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HTML = ROOT / "mind_sandbox.html"
FILES = ("params.mind", "traits.mind", "resolve.mind", "readout.mind")


def tpl(s):
    return "`" + s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${") + "`"


def block():
    js = (ROOT / "web" / "mindmodel.js").read_text(encoding="utf-8").rstrip("\n")
    texts = ",\n".join(' ["%s", %s]' % (f, tpl((ROOT / "mindcore" / "model" / f).read_text(encoding="utf-8"))) for f in FILES)
    return (
        "//MINDMODEL_START generated by tools/build_html.py from web/mindmodel.js and mindcore/model/*.mind; edit those, not this block\n"
        + js + "\n"
        "const MODEL=MindModel.loadFromTexts([\n" + texts + "\n]);\n"
        "const PARAM_DEFS=MODEL.paramTable().map(r=>[r.key,r.label,r.default,r.step||0.01,r.group]);\n"
        "function defaultParams(){const P={};for(const r of PARAM_DEFS)P[r[0]]=r[2];return P;}\n"
        "const TRAITS=MODEL.traitInfo();\n"
        "{const FX=MODEL.traitEffects();for(const k in TRAITS)TRAITS[k].fx=FX[k];}\n"
        "const PERSONA_KEYS=Object.keys(TRAITS);\n"
        "function defaultPersona(){return MODEL.defaultPersona();}\n"
        "// lust_gate is set from cfg.lustGate * lust_mul inside simulate(), so the UI keeps the base value here\n"
        "function effectiveParams(P,persona){const E=Object.assign({},MODEL.effectiveParams(P,persona));E.lust_gate=P.lust_gate;return E;}\n"
        "//MINDMODEL_END\n")


def build(text):
    b = block()
    if "//MINDMODEL_START" in text:
        return re.sub(r"//MINDMODEL_START.*?//MINDMODEL_END\n", lambda m: b, text, count=1, flags=re.S)
    a = re.search(r"const PARAM_DEFS=\[\];.*?\nfunction defaultParams\(\)\{[^\n]*\n", text, flags=re.S)
    t = re.search(r"//TRAITS_START.*?//TRAITS_END[^\n]*\n", text, flags=re.S)
    if not a or not t:
        raise SystemExit("markers not found in mind_sandbox.html")
    return text[:a.start()] + b + text[a.end():t.start()] + text[t.end():]


if __name__ == "__main__":
    cur = HTML.read_text(encoding="utf-8")
    new = build(cur)
    if "--check" in sys.argv:
        sys.exit(0 if new == cur else 1)
    HTML.write_text(new, encoding="utf-8")
    print("mind_sandbox.html updated" if new != cur else "already up to date")
