"""Static tables extracted from mind_sandbox (generated from the HTML; keep in sync)."""
SIGNED = {"mood", "standards_met", "mood_baseline"}
LATENT = ["mood","arousal_tonic","dominance","standards_met","seeking","play","lust_wanting","lust_inhibition","missing_user","bond","competence","self_esteem","arousal_baseline","mood_baseline","recent_success"]
VALUE = ["boredom","task_commitment","sleep_pressure","sleep_debt"]
ALIAS = {"fatigue":"sleep_pressure","tiredness":"sleep_pressure","arousal":"arousal_tonic","commitment":"task_commitment","wanting":"lust_wanting","inhibition":"lust_inhibition","missing":"missing_user","baseline_mood":"mood_baseline","baseline_arousal":"arousal_baseline"}
CODES = {"tool_success":{"succ":1,"eg":0.05,"es":0.08},"tool_failure":{"fail":1,"eg":-0.4,"es":-0.1,"n":0.3},"praise":{"eg":0.5,"ew":0.5,"es":0.3},"conflict":{"eg":-0.5,"ew":-0.7,"es":-0.2,"th":0.3},"joke":{"n":0.4,"ep":0.6,"ew":0.3},"flirt":{"ew":0.3,"el":0.7},"danger":{"th":0.8,"n":0.6},"surprise":{"n":0.7},"warm_moment":{"eg":0.5,"ew":0.6,"ep":0.6}}
CTRLV = ["arousal","seeking","play","lust_wanting","dominance"]
DEFAULTS = {"speed_fast":1,"speed_mid":1,"speed_slow":1,"carry_valence_to_mood":0.4,"carry_phasic_to_arousal":0.08,"carry_standards_to_selfesteem":0.15,"slow_follow_mood":0.35,"slow_follow_arousal":0.25,"mood_avg_hl":1440,"hl_phasic":4,"hl_valence_reaction":8,"hl_threat":10,"hl_surprise":20,"hl_adversity":20,"hl_recent_success":30,"hl_arousal_tonic":60,"hl_mood":360,"hl_dominance":180,"hl_standards":720,"hl_seeking":90,"hl_play":120,"hl_wanting":45,"hl_inhibition":120,"hl_missing":180,"hl_commit":15,"tau_boredom":130,"hl_bond":14400,"hl_competence":2880,"hl_self_esteem":20160,"hl_arousal_baseline":2160,"hl_mood_baseline":4320,"imp_phasic_novelty":0.5,"imp_phasic_threat":0.9,"imp_phasic_erotic":0.4,"imp_phasic_goal":0.2,"imp_phasic_anticipation":0.3,"imp_val_goal":0.15,"imp_val_warm":0.1,"imp_val_standards":0.1,"reunion_relief":0.6,"impulse_cap":0.8,"impulse_budget":1.5,"appraisal_saturation":3,"surprise_gain":0.3,"habituation_strength":0.15,"habituation_half_life":30,"mood_congruence":0.3,"hormone_congruence":0.2,"missing_warmth_boost":0.5,"intensity_bond":1,"freeform_reference":5,"hammer_scale":1,"hammer_half_life":30,"gate_floor_phasic":0.1,"phasic_scale":3,"blunting":1.2,"rumination":0.5,"giveup":0.5,"ctl_on":1,"demand_gain":1.6,"ctl_arousal_comfort":0.6,"ctl_arousal_drain":0.4,"ctl_arousal_rec":300,"ctl_arousal_rebound":2.5,"ctl_arousal_shield":0.8,"ctl_arousal_deriv":6,"ctl_seeking_comfort":0.4,"ctl_seeking_drain":0.5,"ctl_seeking_rec":240,"ctl_seeking_rebound":1.2,"ctl_seeking_shield":0.4,"ctl_seeking_deriv":3,"ctl_play_comfort":0.3,"ctl_play_drain":0.5,"ctl_play_rec":240,"ctl_play_rebound":1,"ctl_play_shield":0,"ctl_play_deriv":2,"ctl_lust_wanting_comfort":0.3,"ctl_lust_wanting_drain":0.8,"ctl_lust_wanting_rec":180,"ctl_lust_wanting_rebound":1.2,"ctl_lust_wanting_shield":0,"ctl_lust_wanting_deriv":2,"ctl_dominance_comfort":0.55,"ctl_dominance_drain":0.3,"ctl_dominance_rec":360,"ctl_dominance_rebound":1,"ctl_dominance_shield":0.6,"ctl_dominance_deriv":2,"strain_threshold":0.75,"strain_gain":1.5,"strain_hl":720,"strain_to_baseline":0.35,"mood_strain_threshold":0.4,"mood_strain_gain":1,"mood_strain_to_baseline":0.6,"spill_arousal":0.15,"spill_mood":0.1,"spill_debt":0.002,"spill_daily_cap":0.6,"boredom_rate":0.8,"reunion_keep":0.4,"missing_ramp":2,"detach_start":4320,"detach_tau":2880,"bond_baseline":0.45,"circ_arousal":0.7,"sleep_pressure_arousal":1.4,"ultradian_amp":0.08,"weather_mood":0.15,"mood_baseline_offset":0.25,"bistable":0,"wanting_deprivation":0.3,"deprivation_scale":2880,"tau_wake":1092,"tau_sleep":252,"load_fatigue":0.0015,"stress_fatigue":0.0008,"light_fatigue":0.3,"moon_sleep":0.3,"clock_anchor":15,"clock_period":24,"phase_gain":0.0015,"anchor_pull":0.01,"sleep_threshold":-0.3,"sleep_standards_boost":1,"lat":48.2,"start_doy":278,"cloud":0.4,"pressure":1013,"weather_swing":0,"moon_on":1,"moon_phase0":5,"cycle_alpha":0,"cycle_start_day":3,"lust_gate":1}
# Trait hooks (match mind_sandbox.html 'Trait hooks (advanced)'); all neutral at these defaults.
for _k, _v in {"cycle_length": 28.0, "cyc_days": 6.0, "cyc_amp": 0.0, "imp_gain": 1.0,
               "tb_arousal": 0.0, "tb_mood": 0.0, "tb_dom": 0.0, "tb_seek": 0.0, "tb_play": 0.0,
               "tb_want": 0.0, "tb_inh": 0.0, "tb_bond": 0.0, "tb_comp": 0.0, "tb_self": 0.0,
               "floor_bond": 0.0, "floor_comp": 0.0, "floor_self": 0.0, "floor_dom": 0.0, "floor_mood": 0.0,
               "cap_inh": 1.0, "lust_mul": 1.0}.items():
    DEFAULTS.setdefault(_k, _v)
